// Mocks generated by Mockito 5.0.10 from annotations
// in mapalus/test/features/search_task/domain/usecases/get_search_task_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mapalus/core/error/failures.dart' as _i5;
import 'package:mapalus/features/search_task/domain/entities/search_task.dart'
    as _i6;
import 'package:mapalus/features/search_task/domain/repositories/search_task_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [SearchTaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTaskRepository extends _i1.Mock
    implements _i3.SearchTaskRepository {
  MockSearchTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SearchTask>> getSearchTask(
          String? title) =>
      (super.noSuchMethod(Invocation.method(#getSearchTask, [title]),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.SearchTask>>.value(
              _FakeEither<_i5.Failure, _i6.SearchTask>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.SearchTask>>);
}
